name: Sergey Karayev
author: Sergey Karayev
description: Sergey Karayev is mostly a CS grad student.
url: http://sergeykarayev.com
highlighter: pygments
permalink: /:title
markdown: kramdown
ordered_categories: [academic, other]
